#!/bin/bash

docker run -it --rm \
        --net host \
        --cpuset-cpus 0 \
        --memory 512mb \
        -v /tmp/.X11-unix/:/tmp/.X11-unix/ \
        -e DISPLAY=$DISPLAY \
        -v $HOME/:/home/developer/ \
	-v /var/lib/dbus/:/var/lib/dbus/ \
        -v /usr/share/fonts/:/usr/share/fonts/ \
        rodrigomiguele/libreoffice "$@"
